<?php
session_start();
require './config/db.php';
require './Clases/Estudios.php';
$id_terapia = $_POST["terapia_id"];
$Con = conectar();
$Estudio = new Estudios($Con);
$resultPaciente = $Estudio->consultarDatosPacientev2($id_terapia);
$datosPaciente = mysqli_fetch_assoc($resultPaciente);
$resultKatona = $Estudio->consultarResultadosKatona($id_terapia);
$datosKatona = mysqli_fetch_all($resultKatona);
$resultSubMG = $Estudio->consultarResultadosSubMG($id_terapia);
$datosSubMG = mysqli_fetch_all($resultSubMG);
$resultSubMF = $Estudio->consultarResultadosSubMF($id_terapia);
$datosSubMF = mysqli_fetch_all($resultSubMF);
$resultTono = $Estudio->consultarResultadosTonoMuscUbi($id_terapia);
$datosTono = mysqli_fetch_all($resultTono);
$resultSignos = $Estudio->consultarResultadosSignosAlarma($id_terapia);
$datosSignos = mysqli_fetch_all($resultSignos);
$resultPostura = $Estudio->consultarResultadosPostura($id_terapia);
$datosPostura = mysqli_fetch_all($resultPostura);
require './vistas/consultarPaciente.view.php';