<?php
    session_start();
    include '../funciones/funciones.php';
    date_default_timezone_set('America/Mexico_City');
    $codigo_paciente =  $_POST["codigo_paciente"];
    $fechaNacimiento = $_POST["fecha_nacimiento_paciente"];
    $semanasEnGestacion = $_POST["semanas_gestacion"];
    $fechaInicioTratamiento = new DateTime();
    $fechaInicioTratamiento = $fechaInicioTratamiento->format('Y-m-d');
    var_dump($_POST);
    echo "<br>";
    echo $fechaInicioTratamiento;
    echo "<br>";
    echo $fechaNacimiento;
    echo "<br>";
    echo $semanasEnGestacion;
    echo "<br>";
    echo $codigo_paciente;
    echo "<br>";
    //calcularEdadCorregidaSemanas();
     echo calcularEdadCronologicaIngreso($fechaInicioTratamiento, $fechaNacimiento);
    echo "<br>";
     echo calcularFechaNacimientoCorregida($fechaNacimiento, $semanasEnGestacion);
